import {Injectable} from '@angular/core';

@Injectable()
export class NutritionService {
    private nutrients = [
        {
            'id': 1,
            'name': 'Frozen yogurt',
            'type': 'Ice cream',
            'calories': 159.0,
            'fat': 6.0,
            'carbs': 24.0,
            'protein': 4.0,
            'sodium': 87.0,
            'calcium': 14.0,
            'iron': 1.0,
            'comments': 'I love froyo!',
        }, {
            'id': 2,
            'name': 'Ice cream sandwich',
            'type': 'Ice cream',
            'calories': 237.0,
            'fat': 9.0,
            'carbs': 37.0,
            'protein': 4.3,
            'sodium': 129.0,
            'calcium': 8.0,
            'iron': 1.0,
        }, {
            'id': 3,
            'name': 'Eclair',
            'type': 'Pastry',
            'calories': 262.0,
            'fat': 16.0,
            'carbs': 24.0,
            'protein': 6.0,
            'sodium': 337.0,
            'calcium': 6.0,
            'iron': 7.0,
        }, {
            'id': 4,
            'name': 'Cupcake',
            'type': 'Pastry',
            'calories': 305.0,
            'fat': 3.7,
            'carbs': 67.0,
            'protein': 4.3,
            'sodium': 413.0,
            'calcium': 3.0,
            'iron': 8.0,
        }, {
            'id': 5,
            'name': 'Jelly bean',
            'type': 'Candy',
            'calories': 375.0,
            'fat': 0.0,
            'carbs': 94.0,
            'protein': 0.0,
            'sodium': 50.0,
            'calcium': 0.0,
            'iron': 0.0,
        }, {
            'id': 6,
            'name': 'Lollipop',
            'type': 'Candy',
            'calories': 392.0,
            'fat': 0.2,
            'carbs': 98.0,
            'protein': 0.0,
            'sodium': 38.0,
            'calcium': 0.0,
            'iron': 2.0,
        }, {
            'id': 7,
            'name': 'Honeycomb',
            'type': 'Other',
            'calories': 408.0,
            'fat': 3.2,
            'carbs': 87.0,
            'protein': 6.5,
            'sodium': 562.0,
            'calcium': 0.0,
            'iron': 45.0,
        }, {
            'id': 8,
            'name': 'Donut',
            'type': 'Pastry',
            'calories': 452.0,
            'fat': 25.0,
            'carbs': 51.0,
            'protein': 4.9,
            'sodium': 326.0,
            'calcium': 2.0,
            'iron': 22.0,
        }, {
            'id': 9,
            'name': 'KitKat',
            'type': 'Candy',
            'calories': 518.0,
            'fat': 26.0,
            'carbs': 65.0,
            'protein': 7.0,
            'sodium': 54.0,
            'calcium': 12.0,
            'iron': 6.0,
        }, {
            'id': 10,
            'name': 'Chocolate',
            'type': 'Candy',
            'calories': 518.0,
            'fat': 26.0,
            'carbs': 65.0,
            'protein': 7.0,
            'sodium': 54.0,
            'calcium': 12.0,
            'iron': 6.0,
        }, {
            'id': 11,
            'name': 'Chamoy',
            'type': 'Candy',
            'calories': 518.0,
            'fat': 26.0,
            'carbs': 65.0,
            'protein': 7.0,
            'sodium': 54.0,
            'calcium': 12.0,
            'iron': 6.0,
        },
        {
            'id': 12,
            'name': 'Oreo',
            'type': 'Cookie',
            'calories': 140,
            'fat': 7.0,
            'carbs': 21.0,
            'protein': 1.0,
            'sodium': 90.0,
            'calcium': 0.0,
            'iron': 6.0,
        },
    ];

    constructor() {
    }

    getNutrients() {
        return this.nutrients;
    }
}
